# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='companyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='companyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.Company'),
            preserve_default=False,
        ),
    ]
