# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_domain_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain_stats',
        ),
    ]
