# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_delete_domain_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(max_length=64)),
                ('query_id', models.IntegerField()),
                ('src_addr', models.CharField(max_length=64)),
                ('dst_addr', models.CharField(max_length=64)),
                ('src_port', models.CharField(max_length=64)),
                ('dst_port', models.CharField(max_length=64)),
                ('qr', models.BooleanField()),
                ('do', models.BooleanField()),
                ('rd', models.BooleanField()),
                ('ra', models.BooleanField()),
            ],
        ),
    ]
