# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_domain_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain_stats',
            name='dst_port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='domain_stats',
            name='src_port',
            field=models.IntegerField(),
        ),
    ]
